meta:
  name: 'McNative English'
  bml: true
  module: 'McNative'
  language:
    name: 'English'
    localizedName: 'English'
    code: 'en'
messages:
  mcnative.prefix: "&8» &6McNative &8|&f"
  mcnative.nopermissions: '&cI''m sorry, but you do not have permission to perform this command. Please contact server administrators if you believe that this is in error.'
  mcnative.command.manage.help: '${mcnative.prefix} &7All available commands&8:
  &7/mcnative version
  &7/mcnative info
  &7/mcnative paste
  &7/mcnative plugin list
  &7/mcnative plugin enable <plugin>
  &7/mcnative plugin disable <plugin>
  &7/mcnative plugin restart <plugin>'
  mcnative.command.manage.version: '${mcnative.prefix} &7Version&8: &c{version}'
  mcnative.command.manage.paste.staring: '${mcnative.prefix} &7Pasting your server log, please wait. '
  mcnative.command.manage.paste.successful: "${mcnative.prefix} &aYou have successful pasted your log\n&8» &c![{url}]({url})"
  mcnative.command.manage.info: '${prefix.user} McNative info:

  &8» &7McNative Version: &c{mcnative.version}
  &8» &7Protocol Version: &c{protocol.version} &8| &c{protocol.edition}
  &8» &7Java version: &c{java.version}

  &8» &7Platform Name: &c{platform.name}
  &8» &7Platform Version: &c{platform.version}
  &8» &7Network: &c{network}

  &8» &7OS Name: &c{os.name}
  &8» &7OS Version: &c{os.version}
  &8» &7OS Arch: &c{os.arch}

  &8» &7Max memory: &c{memory.maximum}
  &8» &7Allocated memory: &c{memory.allocated}
  &8» &7Free memory: &c{memory.free}
  &8» &7Total free memory: &c{memory.free.total}
  &8'
  mcnative.command.manage.plugin.help: '${mcnative.prefix} &7All available plugin commands&8:
  &7/mcnative plugin list
  &7/mcnative plugin enable <plugin>
  &7/mcnative plugin disable <plugin>
  &7/mcnative plugin restart <plugin>
  &7/mcnative plugin load <plugin>
  &7/mcnative plugin unload <plugin>
  &7/mcnative plugin reload <plugin>'
  mcnative.command.manage.plugin.list: '${mcnative.prefix} &7Installed and loaded plugins:
  @for("plugin" in {plugins},${mcnative.command.manage.plugin.list.loop},"\n","\n")'
  mcnative.command.manage.plugin.list.loop: '&8» &a{plugin.name} &8- &cv{plugin.description.version.name} &7by &c{plugin.description.author}'

  mcnative.command.manage.plugin.notfound: '${mcnative.prefix} &7The plugin &c{plugin.name} &7was not found'

  mcnative.command.manage.plugin.enable.starting: '${mcnative.prefix} &7Enabling &7plugin &c{plugin.name} v{plugin.description.version}'
  mcnative.command.manage.plugin.enable.sucessfully: '${mcnative.prefix} &7Successfully enabled plugin &c{plugin.name}'
  mcnative.command.manage.plugin.enable.failed: '${mcnative.prefix} &cFailed enabling plugin &c{plugin.name} &8(&7{error}&8)'

  mcnative.command.manage.plugin.disable.starting: '${mcnative.prefix} &7Disabling &7plugin &c{plugin.name} v{plugin.description.version}'
  mcnative.command.manage.plugin.disable.successfully: '${mcnative.prefix} &7Successfully disabled plugin &c{plugin.name}'
  mcnative.command.manage.plugin.disable.failed: '${mcnative.prefix} &cFailed disabling plugin &c{plugin.name} &8(&7{error}&8)'

  mcnative.command.manage.plugin.load.starting: '${mcnative.prefix} &7Unloading &7plugin &c{plugin.name} v{plugin.description.version}'
  mcnative.command.manage.plugin.load.successfully: '${mcnative.prefix} &7Successfully unloading plugin &c{plugin.name}'
  mcnative.command.manage.plugin.load.failed: '${mcnative.prefix} &cFailed unloading plugin &c{plugin.name} &8(&7{error}&8)'

  mcnative.command.manage.plugin.unload.starting: '${mcnative.prefix} &7Unloading &7plugin &c{plugin.name} v{plugin.description.version}'
  mcnative.command.manage.plugin.unload.successfully: '${mcnative.prefix} &7Successfully unloaded plugin &c{plugin.name}'
  mcnative.command.manage.plugin.unload.failed: '${mcnative.prefix} &cFailed unloading plugin &c{plugin.name} &8(&7{error}&8)'
